### ISSUE TITLE
[WISHLIST] log when a process is killed

### ISSUE THREAD

**Issue by robrwo** [audreyt/plack-middleware-sizelimit#3]
It would be useful to have an option to log when it kills a process.

I have some middleware that does this: https://github.com/robrwo/Plack-Middleware-LogHarakiri but it makes more sense to have a log_when_killed option that does the logging.

**Comment by audreyt** [comment]
Hi, thanks for the suggestion! I just gave you to the commit bit — would you like to push directly the code into this repo (modulo the whitespace changes, if possible) and let me know, so I can get a release out?

**Comment by robrwo** [comment]
I'll work on this. Thanks.
